### ISSUE TITLE
Not working method start

### ISSUE THREAD

**Issue by ildarik081** [firebase/php-jwt#403]
Hello, I am using `firewalls` with `pattern:^/api` to verify the token. But my API requests without a token also pass. The `start` method should not catch them and give a message about it?

```
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - App\Security\JWTAuthenticator
```
